name: Build & Publish Gradle project

on: [push]

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v3
    - name: Setup JDK 17 for x64
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: corretto
        architecture: x64
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Run shadowJar with Gradle Wrapper
      run: ./gradlew shadowJar
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: Package
        path: plugin/build/libs